### ISSUE TITLE
clusterIP is None

### ISSUE THREAD

**Issue by pepedocs** [sanderploegsma/redis-cluster#4]
This is more of a question than an issue actually, what is the reason for setting clusterIP to None? Wouldn't this make the cluster inaccessible to its clients? Nice work by the way.

**Comment by sanderploegsma** [comment]
Have you tried connecting to it? For example:

```
$ kubectl run -it --rm redis-client --image redis /bin/bash
root@redis-7c87d5bf45-blf4j:/data# redis-cli -h redis-cluster -c
redis-cluster:6379> SET foo bar
-> Redirected to slot [12182] located at 10.1.0.6:6379
OK
```

If you want to be able to connect to it from outside the cluster you might change the Service type, but if you're connecting from inside the cluster a headless service works fine.

**Comment by sdan** [comment]
How do you change the service type, and change it to what?

**Comment by nealYangVic** [comment]
headless service perfect fit redirect client strategy used by redis cluster
