### ISSUE TITLE
Issue with Initializing the cluster.

### ISSUE THREAD

**Issue by ShankyRana** [sanderploegsma/redis-cluster#7]
$ kubectl exec -it redis-cluster-0 -- redis-cli --cluster create --cluster-replicas \

Unrecognized option or bad number of args for: '--cluster-replicas'
command terminated with exit code 1

**Comment by sanderploegsma** [comment]
I'm not sure what you did, but if I look at the README it clearly contains a `1` after the `--cluster-replicas` option. You're also missing the rest of the command, by the way.
